title: Interactive Landslide Simulator
description: Research Project under the guidance of <a href="https://faculty.iitmandi.ac.in/~varun/">Prof. Varun Dutt</a> at <a href="http://acslab.org/">Applied Cognitive Science Lab, IIT Mandi</a> (June 2015 - Jul 2017).
show_downloads: false
google_analytics: 'UA-109066326-3'
theme: jekyll-theme-minimal